name: Generate Warriors of Christ Devotional

on:
  schedule:
    - cron: '0 8 * * *'   # 4:00 AM EST
  workflow_dispatch: {}

jobs:
  generate-devotional:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Run devotional generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: node generate-devotional.js

      - name: Commit and push devotional
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "🕊️ Daily devotional for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
